/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.data;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Cat extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2146735649669871719L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Cat\",\"namespace\":\"com.example.data\",\"fields\":[{\"name\":\"breed\",\"type\":{\"type\":\"enum\",\"name\":\"Breed\",\"symbols\":[\"ABYSSINIAN\",\"AMERICAN_SHORTHAIR\",\"BIRMAN\",\"MAINE_COON\",\"ORIENTAL\",\"PERSIAN\",\"RAGDOLL\",\"SIAMESE\",\"SPHYNX\"]}},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Cat> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Cat> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Cat> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Cat> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Cat> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Cat to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Cat from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Cat instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Cat fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private com.example.data.Breed breed;
  private java.lang.String name;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Cat() {}

  /**
   * All-args constructor.
   * @param breed The new value for breed
   * @param name The new value for name
   */
  public Cat(com.example.data.Breed breed, java.lang.String name) {
    this.breed = breed;
    this.name = name;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return breed;
    case 1: return name;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: breed = (com.example.data.Breed)value$; break;
    case 1: name = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'breed' field.
   * @return The value of the 'breed' field.
   */
  public com.example.data.Breed getBreed() {
    return breed;
  }


  /**
   * Sets the value of the 'breed' field.
   * @param value the value to set.
   */
  public void setBreed(com.example.data.Breed value) {
    this.breed = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Creates a new Cat RecordBuilder.
   * @return A new Cat RecordBuilder
   */
  public static com.example.data.Cat.Builder newBuilder() {
    return new com.example.data.Cat.Builder();
  }

  /**
   * Creates a new Cat RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Cat RecordBuilder
   */
  public static com.example.data.Cat.Builder newBuilder(com.example.data.Cat.Builder other) {
    if (other == null) {
      return new com.example.data.Cat.Builder();
    } else {
      return new com.example.data.Cat.Builder(other);
    }
  }

  /**
   * Creates a new Cat RecordBuilder by copying an existing Cat instance.
   * @param other The existing instance to copy.
   * @return A new Cat RecordBuilder
   */
  public static com.example.data.Cat.Builder newBuilder(com.example.data.Cat other) {
    if (other == null) {
      return new com.example.data.Cat.Builder();
    } else {
      return new com.example.data.Cat.Builder(other);
    }
  }

  /**
   * RecordBuilder for Cat instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Cat>
    implements org.apache.avro.data.RecordBuilder<Cat> {

    private com.example.data.Breed breed;
    private java.lang.String name;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.data.Cat.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.breed)) {
        this.breed = data().deepCopy(fields()[0].schema(), other.breed);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Cat instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.data.Cat other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.breed)) {
        this.breed = data().deepCopy(fields()[0].schema(), other.breed);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'breed' field.
      * @return The value.
      */
    public com.example.data.Breed getBreed() {
      return breed;
    }


    /**
      * Sets the value of the 'breed' field.
      * @param value The value of 'breed'.
      * @return This builder.
      */
    public com.example.data.Cat.Builder setBreed(com.example.data.Breed value) {
      validate(fields()[0], value);
      this.breed = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'breed' field has been set.
      * @return True if the 'breed' field has been set, false otherwise.
      */
    public boolean hasBreed() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'breed' field.
      * @return This builder.
      */
    public com.example.data.Cat.Builder clearBreed() {
      breed = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.example.data.Cat.Builder setName(java.lang.String value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.example.data.Cat.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Cat build() {
      try {
        Cat record = new Cat();
        record.breed = fieldSetFlags()[0] ? this.breed : (com.example.data.Breed) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Cat>
    WRITER$ = (org.apache.avro.io.DatumWriter<Cat>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Cat>
    READER$ = (org.apache.avro.io.DatumReader<Cat>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeEnum(this.breed.ordinal());

    out.writeString(this.name);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.breed = com.example.data.Breed.values()[in.readEnum()];

      this.name = in.readString();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.breed = com.example.data.Breed.values()[in.readEnum()];
          break;

        case 1:
          this.name = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










